const bridge=window.AstrBotPluginPage,panel=document.querySelector('#panel');const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function apiGet(p){if(!bridge?.apiGet)throw Error('AstrBot Pages bridge 未就绪');return bridge.apiGet(p)}async function apiPost(p,b){if(!bridge?.apiPost)throw Error('AstrBot Pages bridge 未就绪');return bridge.apiPost(p,b)}function showError(e){panel.innerHTML=`<p class="error">${esc(e.message||e)}</p>`}
async function renderOverview(){const[o,h]=await Promise.all([apiGet('overview'),apiGet('health')]);panel.innerHTML=`<h2>P0.5 / v${esc(o.schema_version)} 概览</h2><div class="grid"><p>关系作用域：<b>${esc(o.relation_scope_mode)}</b></p><p>账户：${esc(o.accounts.total)}（全局 ${esc(o.accounts.global)} / 会话 ${esc(o.accounts.session)}）</p><p>备份：自动 ${esc(o.backups.auto)} / 手动 ${esc(o.backups.manual)} / 迁移 ${esc(o.backups.migration)} / 恢复前 ${esc(o.backups.pre_restore)}</p><p>协议健康：${esc(h.window_days)} 天，${esc(h.total)} 条匿名统计</p></div><p class="hint">只展示结构化运营数据；不返回消息、推理、证据、原因或账户标识。</p>`}
async function renderConfig(){const c=await apiGet('config'),r=c.romance||{},h=c.protocol_health||{},q=c.query_permission||{},safety=c.interaction_safety||{};panel.innerHTML=`<h2>关系弧线 v${esc(c.config_version)} 配置</h2><div class="grid"><label>全局关系<input id="global" type="checkbox" ${c.is_global_relation?'checked':''}></label><label>私聊结算<input id="private" type="checkbox" ${c.private_enabled?'checked':''}></label><label>群聊结算<input id="group" type="checkbox" ${c.group_enabled?'checked':''}></label><label>群聊需 @ / 回复<input id="direct" type="checkbox" ${c.group_require_at_or_reply?'checked':''}></label><label>单轮原始上限<input id="limit" type="number" min="1" max="10" value="${esc(c.raw_delta_limit)}"></label><label>恋爱总闸<input id="romance" type="checkbox" ${r.global_enabled?'checked':''}></label><label>协议健康统计<input id="health" type="checkbox" ${h.enabled?'checked':''}></label><label>健康保留天数<input id="days" type="number" min="1" max="3650" value="${esc(h.retention_days||30)}"></label><label>群聊普通用户查询<input id="query-group" type="checkbox" ${q.group_normal_user?'checked':''}></label><label>私聊普通用户查询<input id="query-private" type="checkbox" ${q.private_normal_user?'checked':''}></label><label>模型安全策略<select id="safety-mode"><option value="administrator_only">仅管理员</option><option value="llm_suggest">仅记录建议</option><option value="llm_auto">自动升高保护</option></select></label></div><p><button id="save">保存</button> <span id="result"></span></p>`;$('#safety-mode').value=safety.llm_mode||'administrator_only';$('#save').onclick=async()=>{await apiPost('config',{is_global_relation:$('#global').checked,private_enabled:$('#private').checked,group_enabled:$('#group').checked,group_require_at_or_reply:$('#direct').checked,raw_delta_limit:Number($('#limit').value),romance:{...r,global_enabled:$('#romance').checked},protocol_health:{enabled:$('#health').checked,retention_days:Number($('#days').value)},query_permission:{group_normal_user:$('#query-group').checked,private_normal_user:$('#query-private').checked},interaction_safety:{llm_mode:$('#safety-mode').value}});$('#result').textContent='已保存';$('#result').className='ok'}}
async function renderAccounts(){const d=await apiGet('accounts'),rows=d.accounts||[],dims=['trust','respect','comfort','closeness','resonance','romance_interest'],labels={trust:'信赖',respect:'认可',comfort:'安心',closeness:'亲近',resonance:'共鸣',romance_interest:'恋爱意向'};panel.innerHTML=`<h2>账户管理</h2><p class="hint">保存会作为一个原子操作提交；账户在此期间被其他互动更新时，请刷新后重试。</p><p><button data-filter="all">全部</button> <button data-filter="global">全局</button> <button data-filter="session">会话</button> <span id="account-result"></span></p><table><tr><th>身份</th><th>scope</th>${dims.map(k=>`<th>${labels[k]}</th>`).join('')}<th>路线</th><th>互动节奏</th><th>操作</th></tr>${rows.map((r,i)=>`<tr data-row="${i}" data-scope="${esc(r.scope_kind)}"><td>${esc(r.identity)}</td><td>${esc(r.scope_kind)}</td>${dims.map(k=>`<td><input data-dimension="${k}" type="number" min="0" max="100" step="0.1" value="${((r.values[k]||0)/10).toFixed(1)}"></td>`).join('')}<td><select data-policy><option value="hidden">隐藏</option><option value="observing">恋爱观察</option><option value="shown">显示恋爱</option></select></td><td><select data-safety><option value="normal">normal</option><option value="slow_down">slow_down</option><option value="pause_intimacy">pause_intimacy</option></select></td><td><button data-save="${i}">保存</button></td></tr>`).join('')}</table>`;rows.forEach((r,i)=>{const tr=panel.querySelector(`[data-row="${i}"]`);tr.querySelector('[data-policy]').value=r.state?.romance_policy||'hidden';tr.querySelector('[data-safety]').value=r.state?.interaction_safety||'normal'});panel.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>panel.querySelectorAll('tr[data-row]').forEach(r=>r.style.display=b.dataset.filter==='all'||r.dataset.scope===b.dataset.filter?'':'none'));panel.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const row=rows[Number(b.dataset.save)],tr=b.closest('tr'),result=$('#account-result');b.disabled=true;try{const values={};tr.querySelectorAll('[data-dimension]').forEach(x=>values[x.dataset.dimension]=x.value);await apiPost('accounts',{action:'update_account',identity:row.identity,scope_kind:row.scope_kind,scope_id:row.scope_id,revision:row.revision,values,romance_policy:tr.querySelector('[data-policy]').value,interaction_safety:tr.querySelector('[data-safety]').value});result.textContent='已保存';result.className='ok';await renderAccounts()}catch(e){result.textContent=e.message||e;result.className='error'}finally{b.disabled=false}})}
const dimLabel={trust:'信赖',respect:'认可',comfort:'安心',closeness:'亲近',resonance:'共鸣',romance_interest:'恋爱意向'};
const sourceLabel={private:'私聊结算',group:'群聊结算',admin:'管理调整',migration:'迁移修复'};
const actorLabel={llm:'模型结算',administrator:'管理员',page_administrator:'面板管理员',migration:'迁移'};
const fmtTime=value=>typeof value==='number'?new Date(value*1000).toLocaleString():String(value||'-');
const fmtDelta=values=>Object.entries(values||{}).map(([key,value])=>`${dimLabel[key]||key} ${value>0?'+':''}${(Number(value)/10).toFixed(1)}`).join('、')||'无数值变化';
const fmtPolicy=policy=>Object.entries(policy||{}).flatMap(([key,notes])=>(notes||[]).map(note=>`${dimLabel[key]||key}：${note}`)).join('、')||'无';
async function renderAudit(){
  const d=await apiGet('audit'),cards=d.cards||[];
  panel.innerHTML=`<h2>审计卡片</h2><p class="hint">仅显示脱敏结构化结果；不展示身份、消息原文、证据、原因或推理。</p><table><tr><th>来源</th><th>范围</th><th>请求 → 实际</th><th>策略</th><th>时间</th></tr>${cards.map(c=>`<tr><td>${esc(actorLabel[c.actor]||sourceLabel[c.source_kind]||c.actor||c.source_kind||'-')}</td><td>${esc(c.scope_kind==='global'?'全局':'会话')}</td><td>${esc(fmtDelta(c.requested))}<br>→ ${esc(fmtDelta(c.applied))}</td><td>${esc(fmtPolicy(c.policy))}</td><td>${esc(fmtTime(c.created_at))}</td></tr>`).join('')||'<tr><td colspan="5">暂无审计卡片</td></tr>'}</table>`;
}
async function renderHealth(){
  const d=await apiGet('health'),rows=d.buckets||[];
  panel.innerHTML=`<h2>协议健康</h2><p class="hint">${esc(d.window_days||0)} 天匿名统计，共 ${esc(d.total||0)} 条；不含用户或消息内容。</p><table><tr><th>结果</th><th>来源</th><th>裸 JSON 恢复</th><th>次数</th></tr>${rows.map(x=>`<tr><td>${esc(x.outcome||'-')}</td><td>${esc(x.source||'-')}</td><td>${x.bare_recovery?'是':'否'}</td><td>${esc(x.count||0)}</td></tr>`).join('')||'<tr><td colspan="4">暂无统计</td></tr>'}</table>`;
}
async function renderMigrations(){
  const d=await apiGet('migrations'),rows=d.entries||[];
  panel.innerHTML=`<h2>迁移记录</h2><p class="hint">当前 SQLite schema：v${esc(d.schema_version||'-')}。</p><table><tr><th>组件</th><th>版本</th><th>保护备份</th><th>时间</th></tr>${rows.map(x=>`<tr><td>${esc(x.component||'-')}</td><td>v${esc(x.from_version??'-')} → v${esc(x.to_version??'-')}</td><td>${esc(x.backup_name||'无')}</td><td>${esc(fmtTime(x.created_at))}</td></tr>`).join('')||'<tr><td colspan="4">暂无迁移记录</td></tr>'}</table>`;
}

async function renderBindings(){const d=await apiGet('bindings'),rows=d.bindings||[];panel.innerHTML=`<h2>正式关系管理</h2><p class="hint">固定类型：${(d.directory||[]).map(x=>esc(x.label)).join('、')}。结束操作保留历史，不删除账本或关系事件。</p><p><button data-binding-filter="all">全部</button> <button data-binding-filter="global">全局</button> <button data-binding-filter="session">会话</button> <span id="binding-result"></span></p><table><tr><th>身份</th><th>scope</th><th>正式关系</th><th>状态</th><th>建立时间</th><th>操作</th></tr>${rows.map((r,i)=>`<tr data-binding-row="${i}" data-scope="${esc(r.scope_kind)}"><td>${esc(r.identity)}</td><td>${esc(r.scope_kind)}</td><td>${esc(r.label)}</td><td>${esc(r.status)}</td><td>${new Date(r.created_at*1000).toLocaleString()}</td><td>${r.status==='active'?`<button data-end-binding="${esc(r.binding_id)}">结束</button>`:'历史保留'}</td></tr>`).join('')}</table>`;panel.querySelectorAll('[data-binding-filter]').forEach(b=>b.onclick=()=>panel.querySelectorAll('tr[data-binding-row]').forEach(r=>r.style.display=b.dataset.bindingFilter==='all'||r.dataset.scope===b.dataset.bindingFilter?'':'none'));panel.querySelectorAll('[data-end-binding]').forEach(b=>b.onclick=async()=>{if(!confirm('结束此正式关系？历史会保留。'))return;const result=$('#binding-result');try{await apiPost('bindings',{action:'end',binding_id:b.dataset.endBinding});result.textContent='已结束，历史已保留';result.className='ok';await renderBindings()}catch(e){result.textContent=e.message||e;result.className='error'}})}
async function renderBackups(){const d=await apiGet('backups');panel.innerHTML=`<h2>备份</h2><button id="backup">创建手动备份</button><p class="hint">auto 才可能被轮换；manual、migration、pre_restore 都受保护。本批次不开放 Pages 恢复/删除。</p><table><tr><th>类别</th><th>文件</th><th>大小</th><th>时间</th></tr>${(d.backups||[]).map(r=>`<tr><td>${esc(r.kind)}</td><td>${esc(r.name)}</td><td>${esc(r.size)}</td><td>${new Date(r.mtime*1000).toLocaleString()}</td></tr>`).join('')}</table>`;$('#backup').onclick=async()=>{await apiPost('backups',{action:'backup_now'});renderBackups()}}
const tabs={overview:renderOverview,config:renderConfig,accounts:renderAccounts,audit:renderAudit,health:renderHealth,migrations:renderMigrations,bindings:renderBindings,backups:renderBackups};
const build='pages-diagnostic-20260827-2040';
const stage=text=>{ panel.textContent=`Relation Arc ${build}: ${text}`; };
window.addEventListener('error',event=>showError(Error(`页面脚本错误：${event.message||'unknown'}`)));
window.addEventListener('unhandledrejection',event=>showError(Error(`页面请求错误：${event.reason?.message||event.reason||'unknown'}`)));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tabs[b.dataset.tab]().catch(showError));
const timeout=(promise,label,ms=8000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(Error(label+' 超时；请刷新页面或查看宿主 Pages 资源。')),ms))]);
async function init(){
  stage('宿主已连接，正在请求配置…');
  if(!bridge?.apiGet) throw Error('AstrBot Pages bridge 未注入。');
  await timeout(bridge.apiGet('config'),'配置 API 请求');
  await renderConfig();
}
stage('脚本已加载，等待宿主连接…');
if(!bridge?.ready) showError(Error('AstrBot Pages bridge 未注入。'));
else timeout(bridge.ready(),'宿主 context').then(init).catch(showError);
